--  Abstract :
--
--  Text_IO for types in SAL.Gen_Math.Gen_DOF_2
--
--  This file is auto-generated by auto_text_io
--  from SAL.Gen_Math.Gen_DOF_2
--
with SAL.Gen_Math.Gen_Text_IO;
with Ada.Text_IO;
generic
   with package Math_Text_IO is new SAL.Gen_Math.Gen_Text_IO;
package SAL.Gen_Math.Gen_DOF_2.Gen_Text_IO is

   procedure Put
      (File                        : in Ada.Text_IO.File_Type;
       Item                        : in Point_Type;
       Single_Line_Record          : in Boolean := True;
       Named_Association_Record    : in Boolean := False;
       Single_Line_Component       : in Boolean := True;
       Named_Association_Component : in Boolean := False);
   procedure Put
      (Item                        : in Point_Type;
       Single_Line_Record          : in Boolean := True;
       Named_Association_Record    : in Boolean := False;
       Single_Line_Component       : in Boolean := True;
       Named_Association_Component : in Boolean := False);
   procedure Put_Item
      (File              : in Ada.Text_IO.File_Type;
       Item              : in Point_Type;
       Single_Line       : in Boolean := False;
       Named_Association : in Boolean := False);

   procedure Get
      (File                        : in     Ada.Text_IO.File_Type;
       Item                        :    out Point_Type;
       Named_Association_Record    : in     Boolean := False;
       Named_Association_Component : in     Boolean := False);
   procedure Get
      (Item                        :    out Point_Type;
       Named_Association_Record    : in     Boolean := False;
       Named_Association_Component : in     Boolean := False);
   procedure Get_Item
      (File              : in     Ada.Text_IO.File_Type;
       Item              :    out Point_Type;
       Named_Association : in     Boolean := False);

   procedure Put
      (File                        : in Ada.Text_IO.File_Type;
       Item                        : in Rectangle_Type;
       Single_Line_Record          : in Boolean := True;
       Named_Association_Record    : in Boolean := False;
       Single_Line_Component       : in Boolean := True;
       Named_Association_Component : in Boolean := False);
   procedure Put
      (Item                        : in Rectangle_Type;
       Single_Line_Record          : in Boolean := True;
       Named_Association_Record    : in Boolean := False;
       Single_Line_Component       : in Boolean := True;
       Named_Association_Component : in Boolean := False);
   procedure Put_Item
      (File              : in Ada.Text_IO.File_Type;
       Item              : in Rectangle_Type;
       Single_Line       : in Boolean := False;
       Named_Association : in Boolean := False);

   procedure Get
      (File                        : in     Ada.Text_IO.File_Type;
       Item                        :    out Rectangle_Type;
       Named_Association_Record    : in     Boolean := False;
       Named_Association_Component : in     Boolean := False);
   procedure Get
      (Item                        :    out Rectangle_Type;
       Named_Association_Record    : in     Boolean := False;
       Named_Association_Component : in     Boolean := False);
   procedure Get_Item
      (File              : in     Ada.Text_IO.File_Type;
       Item              :    out Rectangle_Type;
       Named_Association : in     Boolean := False);

end SAL.Gen_Math.Gen_DOF_2.Gen_Text_IO;
