--  Abstract :
--
--  Text_IO for types in SAL.Gen_Math.Gen_Polynomials
--
--  This file is auto-generated by auto_text_io
--  from SAL.Gen_Math.Gen_Polynomials
--
with SAL.Gen_Array_Text_IO;
with SAL.Gen_Math.Gen_Text_IO;
with Ada.Text_IO;
generic
   with package Math_Text_IO is new SAL.Gen_Math.Gen_Text_IO;
package SAL.Gen_Math.Gen_Polynomials.Gen_Text_IO is

   package Coefficients_Text_IO is new SAL.Gen_Array_Text_IO.Unconstrained_Float_1D
      (Element_Type             => Real_Type,
       Index_Type               => Natural,
       Index_Array_Element_Type => Coefficients_Type,
       Element_Put              => Math_Text_IO.Put,
       Element_Get              => Math_Text_IO.Get);
   procedure Put
      (File  : in Ada.Text_IO.File_Type;
       Item  : in Coefficients_Type;
       Fore  : in Ada.Text_IO.Field := Coefficients_Text_IO.Default_Fore;
       Aft   : in Ada.Text_IO.Field := Coefficients_Text_IO.Default_Aft;
       Exp   : in Ada.Text_IO.Field := Coefficients_Text_IO.Default_Exp;
       Single_Line       : in Boolean := Coefficients_Text_IO.Default_Single_Line;
       Named_Association : in Boolean :=
         Coefficients_Text_IO.Default_Named_Association)
      renames Coefficients_Text_IO.Put;
   procedure Get
      (File  : in     Ada.Text_IO.File_Type;
       Item  :    out Coefficients_Type;
       Width : in     Ada.Text_IO.Field := 0;
       Named_Association : in Boolean :=
         Coefficients_Text_IO.Default_Named_Association)
      renames Coefficients_Text_IO.Get;
   procedure Put
      (Item  : in Coefficients_Type;
       Fore  : in Ada.Text_IO.Field := Coefficients_Text_IO.Default_Fore;
       Aft   : in Ada.Text_IO.Field := Coefficients_Text_IO.Default_Aft;
       Exp   : in Ada.Text_IO.Field := Coefficients_Text_IO.Default_Exp;
       Single_Line       : in Boolean := Coefficients_Text_IO.Default_Single_Line;
       Named_Association : in Boolean :=
         Coefficients_Text_IO.Default_Named_Association)
      renames Coefficients_Text_IO.Put;
   procedure Get
      (Item  :    out Coefficients_Type;
       Width : in     Ada.Text_IO.Field := 0;
       Named_Association : in Boolean :=
         Coefficients_Text_IO.Default_Named_Association)
      renames Coefficients_Text_IO.Get;
   procedure Put_Item
      (File  : in Ada.Text_IO.File_Type;
       Item  : in Coefficients_Type;
       Single_Line       : in Boolean := Coefficients_Text_IO.Default_Single_Line;
       Named_Association : in Boolean :=
         Coefficients_Text_IO.Default_Named_Association)
      renames Coefficients_Text_IO.Put_Item;
   procedure Get_Item
      (File  : in     Ada.Text_IO.File_Type;
       Item  :    out Coefficients_Type;
       Named_Association : in Boolean :=
         Coefficients_Text_IO.Default_Named_Association)
      renames Coefficients_Text_IO.Get_Item;

end SAL.Gen_Math.Gen_Polynomials.Gen_Text_IO;
